baseURL: "https://sandrasungura.github.io/sungura/"
languageCode: "en-us"
title: "Sungura"
canonifyURLs: true
permalinks:
  post: "/post/:year/:month/:title/"
  top: "/:filename/"
minify:
  minifyOutput: true